# Generated by Django 2.2.7 on 2019-11-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_number', models.IntegerField(unique=True, verbose_name='Регистрационный номер')),
                ('nomination', models.CharField(max_length=100, verbose_name='Номинация')),
                ('name_contest', models.CharField(max_length=100, verbose_name='Название конкурса')),
                ('title', models.CharField(max_length=100, verbose_name='Название работы')),
                ('date_reg', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40, verbose_name='ФИО педагога')),
                ('district', models.CharField(max_length=101, verbose_name='Регион')),
                ('school', models.CharField(max_length=150, verbose_name='Образовательное учреждение')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('experience', models.CharField(max_length=10, verbose_name='Стаж')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40, verbose_name='ФИО участника')),
                ('district', models.CharField(max_length=101, verbose_name='Регион')),
                ('age', models.CharField(max_length=5, verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contest')),
            ],
        ),
    ]
