# Generated by Django 2.2.7 on 2019-11-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='mskch_contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Mskch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='city',
            field=models.CharField(blank=True, max_length=101, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='child',
            name='district',
            field=models.CharField(blank=True, max_length=101, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='child',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='child',
            name='fio',
            field=models.CharField(blank=True, max_length=40, verbose_name='ФИО участника'),
        ),
        migrations.AlterField(
            model_name='child',
            name='region',
            field=models.CharField(blank=True, max_length=101, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school',
            field=models.CharField(blank=True, max_length=150, verbose_name='Образовательное учреждение'),
        ),
        migrations.AlterField(
            model_name='mskch',
            name='name_contest',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название конкурса'),
        ),
        migrations.AlterField(
            model_name='mskch',
            name='nomination',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='mskch',
            name='reg_number',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='mskch',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название работы'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(blank=True, max_length=101, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='district',
            field=models.CharField(blank=True, max_length=101, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.CharField(blank=True, max_length=10, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fio',
            field=models.CharField(blank=True, max_length=40, verbose_name='ФИО педагога'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='region',
            field=models.CharField(blank=True, max_length=101, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.CharField(blank=True, max_length=150, verbose_name='Образовательное учреждение'),
        ),
    ]
