# Generated by Django 2.2.7 on 2019-11-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191107_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40, verbose_name='ФИО участника')),
                ('district', models.CharField(max_length=101, verbose_name='Регион')),
                ('age', models.CharField(max_length=5, verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
            ],
        ),
    ]
