# Generated by Django 2.2.7 on 2019-11-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191107_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='mskch_contest',
        ),
        migrations.AddField(
            model_name='mskch',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Teacher'),
            preserve_default=False,
        ),
    ]
