# Generated by Django 2.2.7 on 2019-11-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191113_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mskch',
            name='date_reg',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
