# Generated by Django 2.2.7 on 2019-11-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191113_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='experience',
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.CharField(blank=True, max_length=10, verbose_name='Возрастная категория'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.CharField(blank=True, max_length=150, verbose_name='Образовательная организация'),
        ),
    ]
