# Generated by Django 2.2.7 on 2019-11-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191113_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.CharField(blank=True, max_length=30, verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(blank=True, max_length=101, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fio',
            field=models.CharField(max_length=40, verbose_name='ФИО педагога'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='region',
            field=models.CharField(max_length=101, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.CharField(max_length=150, verbose_name='Образовательная организация'),
        ),
    ]
