# Generated by Django 2.2.7 on 2019-11-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191114_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='mskch',
            name='reg_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
