# Generated by Django 2.2.7 on 2019-11-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mskch_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mskch',
            name='fio_teacher',
            field=models.CharField(blank=True, max_length=40, verbose_name='ФИО Педагога'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='Artakiada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_number', models.IntegerField()),
                ('fio', models.CharField(blank=True, max_length=40, verbose_name='ФИО участника')),
                ('age', models.CharField(blank=True, choices=[('5', '5 лет'), ('6', '6 лет'), ('7', '7 лет'), ('8', '8 лет'), ('9', '9 лет'), ('10', '10 лет'), ('11', '11 лет'), ('12', '12 лет'), ('13', '13 лет'), ('14', '14 лет'), ('15', '15 лет'), ('16', '16 лет'), ('17', '17 лет'), ('18', '18 лет')], max_length=2, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, choices=[('M', 'M'), ('Ж', 'Ж')], max_length=1, verbose_name='Пол')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название работы')),
                ('date_reg', models.DateTimeField(auto_now=True)),
                ('fio_teacher', models.CharField(blank=True, max_length=40, verbose_name='ФИО Педагога')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
