# Generated by Django 2.2.7 on 2019-11-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191114_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Teacher'),
        ),
    ]
