# Generated by Django 2.2.7 on 2019-11-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
