# Generated by Django 2.2.7 on 2019-11-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_nrusheva'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrusheva',
            name='level',
            field=models.CharField(choices=[('0', 'Дошкольник'), ('1', '1 класс'), ('2', '2 класс'), ('3', '3 класс'), ('4', '4 класс'), ('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], default=1, max_length=2, verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
