# Generated by Django 2.2.7 on 2019-11-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_nrusheva_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrusheva',
            name='city',
            field=models.CharField(blank=True, max_length=101, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='nrusheva',
            name='district',
            field=models.CharField(blank=True, max_length=101, verbose_name='Округ'),
        ),
        migrations.AddField(
            model_name='nrusheva',
            name='region',
            field=models.CharField(blank=True, max_length=101, verbose_name='Регион'),
        ),
    ]
