# Generated by Django 2.2.7 on 2019-11-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20191126_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
    ]
