# Generated by Django 2.2.7 on 2019-11-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mymoskvichi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_number', models.IntegerField()),
                ('date_reg', models.DateTimeField(auto_now=True)),
                ('school', models.CharField(max_length=150, verbose_name='Образовательная организация')),
                ('fio', models.CharField(blank=True, max_length=40, verbose_name='ФИО участника')),
                ('fio_teacher', models.CharField(blank=True, max_length=40, verbose_name='ФИО Педагога')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('status', models.CharField(blank=True, choices=[('0', 'Новый уч. 1-тура'), ('1', 'Просмотрен'), ('2', 'Участник 2-тура'), ('3', 'Участник 2-отбор'), ('4', 'Победитель 1 - место'), ('5', 'Призер 2 - место'), ('6', 'Призер 3 - место')], max_length=2, verbose_name='Статус участника')),
                ('region', models.CharField(blank=True, max_length=101, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=101, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=101, verbose_name='Округ')),
                ('theme', models.CharField(choices=[('1', 'Пушкиниана'), ('2', 'От алхимии до химии')], max_length=2, verbose_name='Номинация')),
                ('author_name', models.CharField(max_length=50, verbose_name='Авторское название')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
