# Generated by Django 2.2.7 on 2019-11-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_mymoskvichi_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='fio',
            field=models.CharField(max_length=400, verbose_name='ФИО участника'),
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='fio_teacher',
            field=models.CharField(max_length=400, verbose_name='ФИО Педагога'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='fio',
            field=models.CharField(max_length=400, verbose_name='ФИО участника'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='fio_teacher',
            field=models.CharField(max_length=400, verbose_name='ФИО Педагога'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='fio',
            field=models.CharField(max_length=400, verbose_name='ФИО участника'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='fio_teacher',
            field=models.CharField(max_length=400, verbose_name='ФИО Педагога'),
        ),
    ]
