# Generated by Django 2.2.7 on 2019-11-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20191127_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(max_length=10, verbose_name='Статус'),
        ),
    ]
