# Generated by Django 2.2.7 on 2019-11-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20191129_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.CharField(blank=True, max_length=150, verbose_name='Образовательная организация'),
        ),
    ]
