# Generated by Django 2.2.7 on 2019-11-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20191130_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='region',
            field=models.CharField(blank=True, max_length=101, verbose_name='Регион'),
        ),
    ]
