# Generated by Django 2.2.7 on 2019-12-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20191204_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='reg_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='reg_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='reg_number',
            field=models.CharField(max_length=15),
        ),
    ]
