# Generated by Django 3.0 on 2019-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20191204_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='fio',
            field=models.CharField(max_length=700, verbose_name='ФИО участника'),
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='fio_teacher',
            field=models.CharField(max_length=700, verbose_name='ФИО Педагога'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='fio',
            field=models.CharField(max_length=700, verbose_name='ФИО участника'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='fio_teacher',
            field=models.CharField(max_length=700, verbose_name='ФИО Педагога'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='fio',
            field=models.CharField(max_length=700, verbose_name='ФИО участника'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='fio_teacher',
            field=models.CharField(max_length=700, verbose_name='ФИО Педагога'),
        ),
    ]
