# Generated by Django 3.0 on 2019-12-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20191210_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymoskvichi',
            old_name='theme_dop',
            new_name='theme_extra',
        ),
    ]
